name: Rust Cargo Test for Multiple Directories

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Fuelup
      run: |
        curl https://install.fuel.network | sh

    - name: Modify Path
      run: echo "$HOME/.fuelup/bin:$PATH" >> $GITHUB_PATH

    - name: Set Fuelup environment and add component
      run: |
        fuelup default testnet

    - name: Find directories with forc.toml
      id: find_dirs
      run: |
        dirs=$(find . -type f -name 'forc.toml' -exec dirname {} \; | sed 's|^\./||')
        echo "dirs=$dirs" >> $GITHUB_ENV

    - name: Create build matrix
      id: build_matrix
      run: |
        dirs=$(echo $dirs | tr ' ' '\n' | jq -R . | jq -s .)
        echo "::set-output name=matrix::${dirs}"

  build_each:
    needs: build_and_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.build_and_test.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Fuelup
      run: |
        curl https://install.fuel.network | sh

    - name: Modify Path
      run: echo "$HOME/.fuelup/bin:$PATH" >> $GITHUB_PATH

    - name: Set Fuelup environment and add component
      run: |
        fuelup default testnet

    - name: Build in ${{ matrix.dir }}
      run: |
        cd ${{ matrix.dir }}
        forc build
