name: Rust Cargo Build for Multiple Directories

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [
          'predicate-multisig',
          'primitive_types',
          'tuples',
          'control_flow_if',
          'constants',
          'logging',
          'base_asset',
          'vector',
          'enums',
          'structs',
          'control_flow_while_loop',
          'compound_types',
          'blockchain_types',
          'control_flow_match_statement',
          'solidity_cheatsheet',
          'results',
          'configurable_constants',
          'uniswapv2',
          'options',
          'account_types',
          'hello_sway',
          'functions',
          'cheatsheet',
          'storage_map'
        ]

    name: Build ${{ matrix.dir }}
    steps:
    - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Fuelup
      run: |
        curl https://install.fuel.network | sh

    - name: Modify Path
      run: echo "$HOME/.fuelup/bin:$PATH" >> $GITHUB_PATH

    - name: Set Fuelup environment and add component
      run: |
        fuelup default testnet

    - name: Build in ${{ matrix.dir }}
      run: |
        cd ${{ matrix.dir }}
        forc build
