name: Rust Cargo Build for Multiple Directories

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      matrix_dirs: ${{ steps.set_matrix.outputs.matrix_dirs }}
    steps:
    - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Validate number of directories
      id: set_matrix
      run: |
        expected_dirs='[
          "predicate-multisig",
          "primitive_types",
          "tuples",
          "control_flow_if",
          "constants",
          "logging",
          "base_asset",
          "vector",
          "enums",
          "structs",
          "control_flow_while_loop",
          "compound_types",
          "blockchain_types",
          "control_flow_match_statement",
          "solidity_cheatsheet",
          "results",
          "configurable_constants",
          "uniswapv2",
          "options",
          "account_types",
          "hello_sway",
          "functions",
          "cheatsheet",
          "storage_map",
          "variables"
        ]'
        
        matrix_length=$(echo "$expected_dirs" | jq length)
        dir_count=$(ls -d */ | grep -v .github | wc -l)
        
        if [ $matrix_length -ne $dir_count ]; then
          echo "Error: Number of directories ($matrix_length) does not match the count of directories ($dir_count)"
          exit 1
        else
          echo "Number of directories ($matrix_length) matches the expected count ($dir_count)"
        fi
        
        echo "::set-output name=matrix_dirs::$(echo $expected_dirs | jq -c .)"

  setup:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Fuelup
      run: |
        curl https://install.fuel.network | sh

    - name: Modify Path
      run: echo "$HOME/.fuelup/bin:$PATH" >> $GITHUB_PATH

    - name: Set Fuelup environment and add component
      run: |
        fuelup default latest

    - name: Save cache
      id: cache-key
      run: |
        cache_key=$(date +%s)
        echo "::set-output name=cache-key::$cache_key"

  build:
    needs: [validate, setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.validate.outputs.matrix_dirs) }}
    steps:
    - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Restore setup cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          ~/.rustup
          ~/.fuelup
        key: ${{ needs.setup.outputs.cache-key }}

    - name: Build in ${{ matrix.dir }}
      run: |
        cd ${{ matrix.dir }}
        forc build
