name: Rust Cargo Build for Multiple Directories

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Rust
      uses: actions-rs/toolchain@v1.1.0
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Fuelup
      run: |
        curl https://install.fuel.network | sh

    - name: Modify Path
      run: echo "$HOME/.fuelup/bin:$PATH" >> $GITHUB_PATH

    - name: Set Fuelup environment and add component
      run: |
        fuelup default testnet

    - name: List directories
      run: |
        echo "Directories to be built:"
        for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
          echo "$dir"
        done

    - name: Build all directories
      run: |
        for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
          echo "Building in $dir"
          cd $dir
          forc build
          cd ..
        done
