name: Update Submodule

on:
  schedule:
    - cron: '*/10 * * * *' # Run the workflow every 10 min

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Update submodule
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@example.com"
        cd ./sway-vs-solidity
        git checkout master
        git pull origin master
        cd ../..
        git add ./sway-vs-solidity
        git commit -m "Update sway-vs-solidity submodule to the latest version" || echo "No changes to commit"
        git push origin HEAD
